
BLOCKLIST = [
    "remaster",
    "best of",
    "various artists",
    "remaster",
    "deluxe",
    "60s",
    "70s",
    "80s",
    "90s",
    "60's",
    "70's",
    "80's",
    "90's",
    "seventies",
    "live at",
    "live from",
    "live in",
    "(live",
    " - live",
    "acoustic",
    "greatest hits",
    "greatest classic rock songs",
    "summer viral hits",
    "anthology",
    "expanded edition",
    " collection",
    "collector",
    " anniversary ",
    "rerecord",
    "re-record",
    "premium edition",
    "limited edition"
    "legacy edition",
    "bonus edition",
    "special edition",
    "reissue",
    "the essential",
    "20th century masters",
    "the complete recordings",
    "the complete albums",
    "radio edit",
    "radio mix",
    "radio version",
    "the essential",
    "single version",
    "single edit",
    "single mix",
    "single remix",
    "extended mix",
    "extended version",
    "extended remix",
    "billboard chart hit",
    "one hit wonder",
    "love songs",
    "compilation",
    "love romantic pop songs",  # Marvin Gaye
    # /\d{4} (re)mix/
    # /remixed \d{4}/   # a lot of John Lennon / George Harrison
    "24 hours of r&b",
    "now that's what i call",   # blast from the past
    # hey mickey - not sure why Spotify thinks this came out in 2020
    "from doo-wop to hip-hop",
    "rhino hi-five",
    # /best \d+ - \d+/
    "(reissue)",
    # /vol.? \d+/
    "feelgood adult contemporary",
    "valentines day"
]
